# Generated by Django 5.2.17 on 2026-09-21 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(help_text='Flat number within the wing, e.g. 101, 202.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='society.wing')),
            ],
            options={
                'ordering': ['wing__name', 'flat_number'],
                'constraints': [models.UniqueConstraint(fields=('wing', 'flat_number'), name='unique_flat_number_per_wing')],
            },
        ),
    ]
