# Generated by Django 5.2.17 on 2026-09-21 11:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0002_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('resident_type', models.CharField(choices=[('OWNER', 'Owner'), ('TENANT', 'Tenant')], default='OWNER', max_length=10)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number (without +91 or spaces).', regex='^[6-9][0-9]{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='society.flat')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
