# Generated by Django 5.2.17 on 2026-09-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(help_text='e.g. MH12AB1234. Spaces and hyphens are removed automatically.', max_length=15, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('OTHER', 'Other')], default='FOUR_WHEELER', max_length=15)),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='Model')),
                ('colour', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='residents.resident')),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
    ]
