# Generated by Django 5.2.17 on 2026-09-21 16:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('society', '0002_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number (without +91 or spaces).', regex='^[6-9][0-9]{9}$')])),
                ('vehicle_number', models.CharField(blank=True, help_text='Optional. Spaces and hyphens are removed automatically.', max_length=15)),
                ('expected_date', models.DateField(default=django.utils.timezone.localdate)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='EXPECTED', max_length=12)),
                ('pass_code', models.CharField(editable=False, max_length=9, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='society.flat')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='residents.resident')),
            ],
            options={
                'ordering': ['-expected_date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle_number'], name='visitors_vi_vehicle_87582d_idx'), models.Index(fields=['expected_date'], name='visitors_vi_expecte_0da911_idx')],
            },
        ),
    ]
