# Generated by Django 5.2.17 on 2026-09-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-expected_date', '-created_at'], 'permissions': [('check_in_out_visitor', 'Can check visitors in and out'), ('cancel_visitor', 'Can cancel expected visitors')]},
        ),
    ]
