# Generated by Django 5.2.17 on 2026-09-21 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='As seen at the gate. Spaces and hyphens are removed automatically.', max_length=15)),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=5)),
                ('category', models.CharField(choices=[('REGISTERED', 'Registered'), ('VISITOR', 'Visitor'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, help_text='Linked automatically when the plate matches a registered vehicle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['plate_number'], name='tracking_ve_plate_n_27ee76_idx')],
            },
        ),
    ]
