# Generated by Django 5.2.17 on 2026-09-22 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelog',
            name='visitor',
            field=models.ForeignKey(blank=True, help_text='Linked automatically when the plate matches an expected or checked-in visitor for that day.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_logs', to='visitors.visitor'),
        ),
    ]
